DECLARE @sql NVARCHAR(MAX) = '';
SELECT @sql += 'ALTER SCHEMA dbo TRANSFER db_owner.' + QUOTENAME(TABLE_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'db_owner';
EXEC sp_executesql @sql

SELECT @sql += 'ALTER SCHEMA dbo TRANSFER db_owner.' + QUOTENAME(ROUTINE_NAME) + ';' + CHAR(13)
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_SCHEMA = 'db_owner' AND ROUTINE_TYPE = 'PROCEDURE';
EXEC sp_executesql @sql;