services:
  django_app:
    build: .
    container_name: django_app
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    # command: python manage.py runserver 0.0.0.0:8000
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery worker --app=django_inx_platform --loglevel=info
    volumes:
      - .:/usr/scr/app
    depends_on:
      - django_app
      - redis
  redis:
    image: "redis:7.2-alpine"