# Generated by Django 4.2.5 on 2023-10-03 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
