# Generated by Django 4.2.4 on 2024-01-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_members", "0003_user_sqlapp_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
