# Generated by Django 4.2.4 on 2024-04-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inktechnology",
            name="ribbon_color",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
