# Generated by Django 4.2.4 on 2024-02-03 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="color_number",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
