# Generated by Django 4.2.4 on 2023-12-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="number",
            field=models.CharField(max_length=100),
        ),
    ]
