# Generated by Django 4.2.4 on 2024-04-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0002_alter_inktechnology_ribbon_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product_name",
            field=models.CharField(max_length=100),
        ),
    ]
