# Generated by Django 4.2.4 on 2024-02-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0002_alter_color_color_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="active",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="insurance_value",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
