# Generated by Django 4.2.4 on 2023-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0002_alter_customer_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="sales_org",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="scale_qty_from",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="price",
            name="scale_qty_to",
            field=models.IntegerField(null=True),
        ),
    ]
