# Generated by Django 4.2.4 on 2024-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0003_alter_customer_active_alter_customer_insurance_value",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ke24line",
            name="date",
            field=models.DateField(null=True),
        ),
    ]
