# Generated by Django 4.2.4 on 2023-12-18 15:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0004_storedprocedure_remove_price_scale_qty_from_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="ke30importline",
            old_name="customer1",
            new_name="customer_1",
        ),
        migrations.RenameField(
            model_name="ke30importline",
            old_name="product1",
            new_name="product_1",
        ),
    ]
