# Generated by Django 4.2.4 on 2024-02-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0004_alter_ke24line_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="has_colors",
            field=models.BooleanField(default=False),
        ),
    ]
