# Generated by Django 4.2.4 on 2024-04-29 16:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0005_rename_budgetforecastdetails_sales_budgetforecastdetail_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="budgetforecastdetail",
            options={
                "verbose_name": "Budget Forecast Detail",
                "verbose_name_plural": "Budget Forecast Details",
            },
        ),
        migrations.AlterModelOptions(
            name="budgetforecastdetail_sales",
            options={
                "verbose_name": "Budget Forecast, Sales",
                "verbose_name_plural": "Budget Forcast, Sales",
            },
        ),
        migrations.RenameField(
            model_name="budgetforecastdetail",
            old_name="scanario",
            new_name="scenario",
        ),
        migrations.RenameField(
            model_name="budgetforecastdetail_sales",
            old_name="scanario",
            new_name="scenario",
        ),
    ]
