# Generated by Django 4.2.4 on 2024-01-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0005_rename_customer1_ke30importline_customer_1_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productstatus",
            name="color_a",
            field=models.IntegerField(null=True),
        ),
    ]
