# Generated by Django 4.2.4 on 2024-02-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0005_brand_has_colors"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file_color",
            field=models.CharField(default="blue", max_length=20, null=True),
        ),
    ]
