# Generated by Django 4.2.4 on 2024-02-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0006_uploadedfile_file_color"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="storedprocedure",
            options={
                "verbose_name": "Stored Procedure",
                "verbose_name_plural": "Stored Procedures",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="approved_on",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="import_note",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="import_status",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
