# Generated by Django 4.2.4 on 2024-05-07 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0006_alter_budgetforecastdetail_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="countrycode",
            options={"ordering": ["alpha_2"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name"]},
        ),
        migrations.RenameField(
            model_name="countrycode",
            old_name="iso3166_1_alpha_2",
            new_name="alpha_2",
        ),
        migrations.RenameField(
            model_name="countrycode",
            old_name="iso3166_1_alpha_3",
            new_name="alpha_3",
        ),
    ]
