# Generated by Django 4.2.4 on 2024-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0006_productstatus_color_a"),
    ]

    operations = [
        migrations.AddField(
            model_name="zacodmi9_import_line",
            name="import_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
