# Generated by Django 4.2.4 on 2024-05-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0007_alter_countrycode_options_alter_product_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("NEW", "new"),
                    ("PROCESSING", "processing"),
                    ("PROCESSED", "processed"),
                ],
                default="NEW",
                max_length=40,
            ),
        ),
    ]
