# Generated by Django 4.2.4 on 2024-02-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0007_alter_storedprocedure_options_product_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="import_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="import_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
