# Generated by Django 4.2.4 on 2024-01-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0007_zacodmi9_import_line_import_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="approved_by_old",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
