# Generated by Django 4.2.4 on 2024-05-10 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inx_platform_app.models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0008_uploadedfile_process_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadedFileLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "file_name",
                    models.FilePathField(
                        match=".*\\.(xlsx|XLSX)$",
                        path=pathlib.PurePosixPath(
                            "/Users/marco/Library/CloudStorage/Dropbox/_dev/inx_platform_proj/media_root"
                        ),
                        validators=[inx_platform_app.models.xls_xlsx_file_validator],
                    ),
                ),
                ("log_text", models.TextField()),
                (
                    "uploaded_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.uploadedfile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
