# Generated by Django 4.2.4 on 2024-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0008_alter_product_import_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="credit_limit",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="import_note",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="import_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="vat",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
