# Generated by Django 4.2.4 on 2024-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0008_customer_approved_by_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="sqlapp_id",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
