# Generated by Django 4.2.4 on 2024-05-13 14:11

from django.db import migrations, models
import inx_platform_app.models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0009_uploadedfilelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfilelog",
            name="file_path",
            field=models.FilePathField(
                default="ciao",
                match=".*\\.(xlsx|XLSX)$",
                path=pathlib.PurePosixPath(
                    "/Users/marco/Library/CloudStorage/Dropbox/_dev/django_inx_platform/media_root"
                ),
                validators=[inx_platform_app.models.xls_xlsx_file_validator],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="file_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
