# Generated by Django 4.2.4 on 2024-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0009_alter_customer_credit_limit_alter_customer_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="countrycode",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
