# Generated by Django 4.2.4 on 2024-05-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0010_uploadedfilelog_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfilelog",
            name="celery_task_id",
            field=models.CharField(default="older", max_length=255),
            preserve_default=False,
        ),
    ]
