# Generated by Django 4.2.4 on 2024-02-25 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0010_alter_countrycode_sqlapp_id_alter_customer_sqlapp_id",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="approved_on",
            field=models.DateField(null=True),
        ),
    ]
