# Generated by Django 4.2.4 on 2024-05-17 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import inx_platform_app.models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0011_uploadedfilelog_celery_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="celery_task_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="file_path",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(xlsx|XLSX)$",
                null=True,
                path=pathlib.PurePosixPath(
                    "/Users/marco/Library/CloudStorage/Dropbox/_dev/django_inx_platform/media_root"
                ),
                validators=[inx_platform_app.models.xls_xlsx_file_validator],
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="log_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="uploaded_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.uploadedfile",
            ),
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
