# Generated by Django 4.2.4 on 2024-02-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0011_customer_is_new_alter_customer_approved_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="approved_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
