# Generated by Django 4.2.4 on 2024-02-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0013_customer_phone_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inx_platform_app.customer",
            ),
        ),
    ]
