# Generated by Django 4.2.4 on 2024-05-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0013_budgetforecastdetail_brand_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="is_budget",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="is_forecast",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="is_mtp",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
