# Generated by Django 4.2.4 on 2024-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0015_currency_alter_exchangerate_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="symbol",
            field=models.CharField(max_length=2),
        ),
    ]
