# Generated by Django 4.2.4 on 2024-02-28 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0016_inktechnology_short_name_alter_inktechnology_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="inktechnology",
            name="ribbon_color",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
