# Generated by Django 4.2.4 on 2024-06-06 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0017_rename_currency_customer_currency_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.currency",
            ),
        ),
    ]
