# Generated by Django 4.2.4 on 2024-02-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0017_inktechnology_ribbon_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="majorlabel",
            name="sap_id",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="majorlabel",
            name="sap_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="majorlabel",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
