# Generated by Django 4.2.4 on 2024-06-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0018_customer_currency"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name_plural": "Currencies"},
        ),
        migrations.AddField(
            model_name="currency",
            name="svg_symbol",
            field=models.TextField(null=True),
        ),
    ]
