# Generated by Django 4.2.4 on 2024-02-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0019_paymentterm_shippingpolicy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="title",
            field=models.CharField(
                choices=[
                    ("NO_TITLE", ""),
                    ("MR", "Mr."),
                    ("MRS", "Mrs."),
                    ("MS", "Ms."),
                    ("DR", "Dr."),
                    ("PROF", "Prof."),
                ],
                default="NO_TITLE",
                max_length=10,
            ),
        ),
    ]
