# Generated by Django 4.2.4 on 2024-06-24 06:52

from django.db import migrations, models
import inx_platform_app.models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0020_alter_uploadedfilelog_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="budget_open",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="file_path",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(xlsx|XLSX)$",
                null=True,
                path=pathlib.PurePosixPath(
                    "/Users/marco/Library/CloudStorage/Dropbox/_dev/inx_platform_proj/media_root"
                ),
                validators=[inx_platform_app.models.xls_xlsx_file_validator],
            ),
        ),
    ]
