# Generated by Django 4.2.4 on 2024-06-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0021_user_budget_open_alter_uploadedfilelog_file_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
