# Generated by Django 4.2.4 on 2024-06-24 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0022_contacttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="contact_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.contacttype",
            ),
        ),
    ]
