# Generated by Django 4.2.4 on 2024-02-29 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0023_customernote_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="approved_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
