# Generated by Django 4.2.4 on 2024-06-27 11:37

from django.db import migrations, models
import inx_platform_app.models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0023_contact_contact_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfilelog',
            name='file_path',
            field=models.FilePathField(blank=True, match='.*\\.(xlsx|XLSX)$', null=True, path=pathlib.PurePosixPath('/home/marco/inx_platform/media_root'), validators=[inx_platform_app.models.xls_xlsx_file_validator]),
        ),
    ]