# Generated by Django 4.2.4 on 2024-07-04 15:28

from django.db import migrations, models
import django.db.models.deletion
import inx_platform_app.models
import pathlib


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0024_alter_uploadedfilelog_file_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfilelog",
            name="file_path",
            field=models.FilePathField(
                blank=True,
                match=".*\\.(xlsx|XLSX)$",
                null=True,
                path=pathlib.PurePosixPath(
                    "/Users/marco/Library/CloudStorage/Dropbox/_dev/django_inx_platform/media_root"
                ),
                validators=[inx_platform_app.models.xls_xlsx_file_validator],
            ),
        ),
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=6)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inx_platform_app.currency",
                    ),
                ),
            ],
        ),
    ]
