# Generated by Django 4.2.4 on 2024-03-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0025_alter_brand_sap_id_alter_brand_sap_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["last_name"]},
        ),
        migrations.CreateModel(
            name="Fert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=6)),
                ("is_active", models.BooleanField(default=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_on", models.DateTimeField()),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.brand",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.division",
                    ),
                ),
                (
                    "ink_technology",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.inktechnology",
                    ),
                ),
                (
                    "major_label",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.majorlabel",
                    ),
                ),
                (
                    "market_segment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.marketsegment",
                    ),
                ),
                (
                    "material_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.materialgroup",
                    ),
                ),
                (
                    "nsf_division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inx_platform_app.nsfdivision",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
            },
        ),
    ]
