# Generated by Django 4.2.4 on 2024-07-04 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0025_alter_uploadedfilelog_file_path_currencyrate"),
    ]

    operations = [
        migrations.CreateModel(
            name="EuroExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("rate", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.currency",
                    ),
                ),
            ],
            options={
                "unique_together": {("currency", "year", "month")},
            },
        ),
    ]
