# Generated by Django 4.2.4 on 2024-07-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0026_euroexchangerate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackagingRateToLiter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_of_measure", models.CharField(max_length=10)),
                ("rate_to_liter", models.SmallIntegerField()),
                (
                    "packaging",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inx_platform_app.packaging",
                    ),
                ),
            ],
        ),
    ]
