# Generated by Django 4.2.4 on 2024-03-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0026_alter_contact_options_fert"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="log",
            field=models.TextField(blank=True, null=True),
        ),
    ]
