# Generated by Django 4.2.4 on 2024-07-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0028_alter_packagingratetoliter_rate_to_liter"),
    ]

    operations = [
        migrations.AddField(
            model_name="packaging",
            name="base_unit_of_measure",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.unitofmeasure",
            ),
            preserve_default=False,
        ),
    ]
