# Generated by Django 4.2.4 on 2024-07-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0029_packaging_base_unit_of_measure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="product_number",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
