# Generated by Django 4.2.4 on 2024-03-11 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0030_alter_product_brand_alter_product_packaging_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["name"]},
        ),
    ]
