# Generated by Django 4.2.4 on 2024-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0031_alter_customer_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
