# Generated by Django 4.2.4 on 2024-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0032_user_mobile_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="currency",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
