# Generated by Django 4.2.4 on 2024-07-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0033_budgetforecastdetail_price_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetforecastdetail",
            name="price_old",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail",
            name="value_old",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail",
            name="volume_old",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail_sales",
            name="price_old",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail_sales",
            name="value_old",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail_sales",
            name="volume_old",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
