# Generated by Django 4.2.4 on 2024-03-13 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0033_alter_customer_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.countrycode",
            ),
        ),
    ]
