# Generated by Django 4.2.4 on 2024-07-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0034_alter_budgetforecastdetail_price_old_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetforecastdetail",
            name="currency_zaq",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail_sales",
            name="currency_zaq",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
