# Generated by Django 4.2.4 on 2024-03-13 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0034_alter_customer_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="sales_employee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_manager",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
