# Generated by Django 4.2.4 on 2024-03-17 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0035_alter_customer_sales_employee"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ZACODMI9_import_line",
            new_name="ZAQCODMI9_import_line",
        ),
        migrations.RenameModel(
            old_name="ZACODMI9_line",
            new_name="ZAQCODMI9_line",
        ),
    ]
