# Generated by Django 4.2.4 on 2024-08-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0035_alter_budgetforecastdetail_currency_zaq_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_number", models.IntegerField()),
                (
                    "component_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("component_uom_in_bom", models.CharField(max_length=5)),
                ("price_unit", models.IntegerField()),
                (
                    "standard_price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BomComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("component_material", models.CharField(max_length=30, unique=True)),
                ("component_base_uom", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="BomHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alt_bom", models.IntegerField()),
                (
                    "header_base_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("header_base_quantity_uom", models.CharField(max_length=5)),
            ],
        ),
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["name"]},
        ),
        migrations.AlterUniqueTogether(
            name="euroexchangerate",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="budforline",
            constraint=models.UniqueConstraint(
                fields=("customer", "brand", "color_group"),
                name="unique_Customer_brand_colorgroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="euroexchangerate",
            constraint=models.UniqueConstraint(
                fields=("currency", "year", "month"), name="unique_currency_year_month"
            ),
        ),
        migrations.AddConstraint(
            model_name="exchangerate",
            constraint=models.UniqueConstraint(
                fields=("currency", "year"), name="unique_currency_year"
            ),
        ),
        migrations.AddField(
            model_name="bomheader",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.product",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="bom_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.bomcomponent",
            ),
        ),
        migrations.AddField(
            model_name="bom",
            name="bom_header",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="inx_platform_app.bomheader",
            ),
        ),
        migrations.AddConstraint(
            model_name="bomheader",
            constraint=models.UniqueConstraint(
                fields=("product", "alt_bom"), name="unique_product_altbom"
            ),
        ),
    ]
