# Generated by Django 4.2.4 on 2024-03-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0037_scenario_is_sales"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("script", models.TextField()),
            ],
            options={
                "verbose_name": "Database View",
                "verbose_name_plural": "Database Views",
            },
        ),
    ]
