# Generated by Django 4.2.4 on 2024-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0039_remove_bomheader_unique_product_altbom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bomheader",
            name="alt_bom",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
