# Generated by Django 4.2.4 on 2024-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0040_alter_bomheader_alt_bom"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bomheader",
            constraint=models.UniqueConstraint(
                fields=("product", "alt_bom"), name="unique_product_altbom"
            ),
        ),
    ]
