# Generated by Django 4.2.4 on 2024-08-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0041_bomheader_unique_product_altbom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="bom_component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.bomcomponent",
            ),
        ),
        migrations.AlterField(
            model_name="bom",
            name="bom_header",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.bomheader",
            ),
        ),
        migrations.AlterField(
            model_name="bomheader",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.product",
            ),
        ),
    ]
