# Generated by Django 4.2.4 on 2024-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0042_alter_bom_bom_component_alter_bom_bom_header_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="item_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
