# Generated by Django 4.2.4 on 2024-08-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0044_product_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.AddField(
            model_name="productstatus",
            name="marked_for_deletion",
            field=models.BooleanField(default=False),
        ),
    ]
