# Generated by Django 4.2.4 on 2024-08-19 13:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0046_alter_productstatus_color_a_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productstatus",
            options={"verbose_name_plural": "Product Statuses"},
        ),
    ]
