# Generated by Django 4.2.4 on 2024-08-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0048_alter_uploadedfilelog_file_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="component_base_uom",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="bom",
            name="component_uom_in_bom",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
