# Generated by Django 4.2.4 on 2024-08-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0049_bom_component_base_uom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="standard_price_per_unit_EUR",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
