# Generated by Django 4.2.4 on 2024-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0050_bom_standard_price_per_unit_eur"),
    ]

    operations = [
        migrations.AddField(
            model_name="bomheader",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
