# Generated by Django 4.2.4 on 2024-09-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0053_bomcomponent_is_fert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budfordetailline",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budforline",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budfornote",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="budgetforecastdetail_sales",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="color_number",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="color",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="colorgroup",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="customertype",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="division",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="industry",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="madein",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="marketsegment",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="materialgroup",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="nsfdivision",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="packaging",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="ratetolt",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="unitofmeasure",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sqlapp_id",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
