# Generated by Django 4.2.4 on 2024-09-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0054_alter_budfordetailline_sqlapp_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unitofmeasure",
            name="name",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.CreateModel(
            name="UnitOfMeasureConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "uom_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_from",
                        to="inx_platform_app.unitofmeasure",
                    ),
                ),
                (
                    "uom_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uom_to",
                        to="inx_platform_app.unitofmeasure",
                    ),
                ),
            ],
        ),
    ]
