# Generated by Django 4.2.4 on 2024-09-08 16:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0055_alter_unitofmeasure_name_unitofmeasureconversionrate",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UnitOfMeasureConversionRate",
            new_name="UnitOfMeasureConversionFactor",
        ),
    ]
