# Generated by Django 4.2.4 on 2024-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0056_rename_unitofmeasureconversionrate_unitofmeasureconversionfactor",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="bom",
            name="standard_price_per_kg_ea",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bom",
            name="standard_price_per_kg_ea_EUR",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bom",
            name="uom_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="bom",
            name="weighed_price_per_kg_ea_EUR",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
