# Generated by Django 4.2.4 on 2024-09-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0057_bom_standard_price_per_kg_ea_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bom",
            old_name="standard_price_per_kg_ea",
            new_name="standard_price_per_kg_ea_CZK",
        ),
        migrations.RenameField(
            model_name="bom",
            old_name="standard_price_per_unit",
            new_name="standard_price_per_unit_CZK",
        ),
        migrations.AddField(
            model_name="bom",
            name="weighed_price_per_kg_ea_CZK",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
