# Generated by Django 4.2.4 on 2024-09-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0059_alter_unitofmeasureconversionfactor_factor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bom",
            name="uom_factor",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
