# Generated by Django 4.2.4 on 2024-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0060_alter_bom_uom_factor"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("number",), name="unique_product_number"
            ),
        ),
    ]
