# Generated by Django 4.2.4 on 2024-09-17 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0061_product_unique_product_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("rmc_perc", models.DecimalField(decimal_places=2, max_digits=5)),
                ("conv_perc", models.DecimalField(decimal_places=2, max_digits=5)),
                ("active", models.BooleanField(default=False)),
                (
                    "nsf_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.nsfdivision",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.scenario",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="manualcost",
            constraint=models.UniqueConstraint(
                fields=("nsf_division", "year"), name="unique_nsf_division_year"
            ),
        ),
    ]
