# Generated by Django 4.2.4 on 2024-10-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0062_manualcost_manualcost_unique_nsf_division_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="customer_product_number",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
