# Generated by Django 4.2.4 on 2024-10-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0063_product_customer_product_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="customer_product_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
