# Generated by Django 4.2.4 on 2024-10-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0064_alter_product_customer_product_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="process_status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("PROCESSING", "Processing"),
                    ("UPLOAD_DONE", "Upload done"),
                    ("PROCESSED", "Processed"),
                    ("ERROR", "Error"),
                    ("COMPLETE", "Complete"),
                ],
                default="NEW",
                max_length=40,
            ),
        ),
    ]
