# Generated by Django 4.2.4 on 2024-10-16 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0065_alter_uploadedfile_process_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="budgetforecastdetail",
            name="date_time_mark",
            field=models.BigIntegerField(blank=True, default=20241014235900),
        ),
        migrations.AddField(
            model_name="budgetforecastdetail",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budgetforecastdetail",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="budgetforecastdetail_sales",
            name="date_time_mark",
            field=models.BigIntegerField(blank=True, default=20241014235900),
        ),
        migrations.AddField(
            model_name="budgetforecastdetail_sales",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="budgetforecastdetail_sales",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
