# Generated by Django 4.2.4 on 2024-11-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0066_alter_uploadedfile_options_rebate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iso_639_1", models.CharField(max_length=2, unique=True)),
                ("iso_639_2", models.CharField(blank=True, max_length=3, null=True)),
                ("family", models.CharField(blank=True, max_length=50, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "native_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("wiki_url", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField(auto_now=True)),
                ("rtf_content", models.TextField(blank=True, null=True)),
                ("logo_width", models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="customer_logos/"),
        ),
        migrations.CreateModel(
            name="ProductLanguageReplacements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_for", models.CharField(max_length=200)),
                ("replace_with", models.CharField(max_length=200)),
                (
                    "product_language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.productlanguage",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="productlanguage",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.customer",
            ),
        ),
        migrations.AddField(
            model_name="productlanguage",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.language",
            ),
        ),
        migrations.AddField(
            model_name="productlanguage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="inx_platform_app.product",
            ),
        ),
    ]
