# Generated by Django 4.2.4 on 2024-11-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0066_alter_uploadedfile_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastBudgetNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time_mark", models.BigIntegerField()),
                ("note", models.TextField()),
                (
                    "budforline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.budforline",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inx_platform_app.scenario",
                    ),
                ),
            ],
        ),
    ]
