# Generated by Django 4.2.4 on 2024-11-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0067_language_productlanguage_customer_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlanguage",
            name="logo_width",
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name="productlanguage",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
