# Generated by Django 4.2.4 on 2024-11-13 06:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inx_platform_app", "0068_alter_productlanguage_logo_width_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductLanguageReplacements",
            new_name="ProductLanguageReplacement",
        ),
    ]
