# Generated by Django 4.2.4 on 2024-11-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inx_platform_app",
            "0069_rename_productlanguagereplacements_productlanguagereplacement",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productlanguagereplacement",
            name="replace_with",
            field=models.TextField(),
        ),
    ]
