# Generated by Django 4.2.4 on 2024-11-21 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0070_alter_productlanguagereplacement_replace_with'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLanguageReplacement',
        ),
    ]
