# Generated by Django 4.2.4 on 2024-11-21 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0071_delete_productlanguagereplacement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductLanguage',
        ),
    ]
