# Generated by Django 4.2.4 on 2024-11-21 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0072_delete_productlanguage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDSReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_for', models.TextField()),
                ('replace_with', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inx_platform_app.customer')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inx_platform_app.language')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inx_platform_app.product')),
            ],
            options={
                'db_table': 'sds_replacement',
            },
        ),
    ]
