# Generated by Django 4.2.4 on 2024-11-21 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0073_sdsreplacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdsreplacement',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inx_platform_app.language'),
        ),
        migrations.AlterField(
            model_name='sdsreplacement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inx_platform_app.product'),
        ),
    ]
