# Generated by Django 4.2.4 on 2024-12-12 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0074_alter_sdsreplacement_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inx_platform_app.customer'),
        ),
    ]
