# Generated by Django 4.2.4 on 2024-12-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0075_product_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='majorlabel',
            name='oem',
            field=models.BooleanField(default=False),
        ),
    ]
