# Generated by Django 4.2.4 on 2024-12-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0077_sdsrtffile_sdsrtffile_unique_product_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdsrtffile',
            name='file_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
