# Generated by Django 4.2.4 on 2024-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0078_alter_sdsrtffile_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo_width_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
