# Generated by Django 4.2.4 on 2025-01-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0079_customer_logo_width_mm'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='logo_baseline_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='logo_left_margin_mm',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
