# Generated by Django 4.2.4 on 2025-01-02 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inx_platform_app', '0080_customer_logo_baseline_mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inx_platform_app.customer'),
        ),
    ]
